### ISSUE TITLE
MSVC 2019 error about casting

### ISSUE THREAD

**Issue by donizettilorenzo** [Think-Silicon/GLOVE#86] opened 2020-01-21 11:51 UTC
*Lastest Vulkan SDK
*Lastest MSVC 2019 CE
*x86 release build

-> https://postimg.cc/XBCnDdRb

**Comment by dgeorg79** [comment] 2020-01-21 12:06
Hi,

  This is interesting, it didn't happen in our environment. We will try to reproduce, thanks for reporting

**Comment by dgeorg79** [comment] 2020-01-22 09:51
Hi again,

Unfortunately, I could not easily reproduce your problem, but I assume it is caused by KHRONOS definition of non-dispatchable object - see [here](https://github.com/KhronosGroup/Vulkan-Headers/blob/master/include/vulkan/vulkan_core.h#L57).

An easy solution to this problem would be the patch [depthBufferPatch.txt](https://github.com/Think-Silicon/GLOVE/files/4096299/depthBufferPatch.txt).

```
index 616595f..32774dc 100644
--- a/EGL/include/rendering_api_interface.h
+++ b/EGL/include/rendering_api_interface.h
@@ -38,7 +38,7 @@ extern "C" {
 typedef struct EGLSurfaceInterface_t {
     void    *surface;
     void    *images;
-    uint64_t depthBuffer;
+    void    *depthBuffer;
     int32_t  contextRef;
     uint32_t imageCount;
     uint32_t nextImageIndex;
diff --git a/GLES/source/context/context.cpp b/GLES/source/context/context.cpp
index 88125e8..4f3c902 100644
--- a/GLES/source/context/context.cpp
+++ b/GLES/source/context/context.cpp
@@ -237,7 +237,7 @@ Context::CreateDepthStencil(EGLSurfaceInterface *eglSurfaceInterface)
             return nullptr;
         }
         VkImage vkImage = tex->GetImage()->GetImage();
-        eglSurfaceInterface->depthBuffer = reinterpret_cast<uint64_t>(vkImage);
+        eglSurfaceInterface->depthBuffer = reinterpret_cast<void *>(vkImage);
         tex->SetVkImage(vkImage);
     } else {
         VkImage vkImage = reinterpret_cast<VkImage>(eglSurfaceInterface->depthBuffer);
```

Could you try to re-compile GLOVE after applying the patch? If the problem is solved I will commit it to master. 

In case you find other problems, please report it here - to the same issue

Thanks :wink:

**Comment by donizettilorenzo** [comment] 2020-01-22 10:47
Compiling now goes well, I only have a linking problem to solve :p ('cause
I created an x86 target release)

Error LNK1112 module machine type 'x64' conflicts with target machine type
'x86' D:\Projects\GLOVE-0.4\out\build\x86-Release\GLOVE-0.4
D:\Projects\GLOVE-0.4\out\build\x86-Release\glslang.lib(ShaderLang.obj) 1

Il giorno mer 22 gen 2020 alle ore 10:51 Dimitris Georgakakis <
notifications@github.com> ha scritto:

**Comment by donizettilorenzo** [comment] 2020-01-22 10:53
x64 release is perfectly working ;)

[image: Untitled.jpg]

About "complete" OpenGL wrapping.....any chance for the future from your
GLOVE project or we must wait for Zink (MESA Gallium based)?

**Comment by dgeorg79** [comment] 2020-01-22 10:57
I cannot see the image. Did you run the GLOVE demos?

**Comment by donizettilorenzo** [comment] 2020-01-22 11:44
Yes! ^_^

Il giorno mer 22 gen 2020 alle ore 11:57 Dimitris Georgakakis <
notifications@github.com> ha scritto:

**Comment by dgeorg79** [comment] 2020-01-22 13:04
To answer your question, Think Silicon's next plans for GLOVE is to support GL ES 3.x for embedded devices. Desktop OpenGL support might come later.

On the other hand, GLOVE SW design allows extending the code to support desktop OpenGL. Therefore, in case some external contributor would like to try, we would be more than happy to help and coordinate.

**Comment by donizettilorenzo** [comment] 2020-01-22 13:13
Thanks!

Il giorno mer 22 gen 2020 alle ore 14:04 Dimitris Georgakakis <
notifications@github.com> ha scritto:

**Comment by dgeorg79** [comment] 2020-01-22 13:19
Closing the issue with commit 3b0efffcb8fc7c0e736cbca56270c83af92c4e2c

**Closed** 2020-01-22 13:26 UTC
Labels: GLES
